// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVoaSbNjXGUn2q8PY1iIJNe4XfNctwTeo',
    appId: '1:889900014128:web:6802a0e4d82168b42cebf5',
    messagingSenderId: '889900014128',
    projectId: 'nora-3e220',
    authDomain: 'nora-3e220.firebaseapp.com',
    storageBucket: 'nora-3e220.firebasestorage.app',
    measurementId: 'G-Q3JBLEYBH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNZvw9tjaFajaSGr9CIlTmIUPYrk3AiR8',
    appId: '1:889900014128:android:ce160963db20dd9e2cebf5',
    messagingSenderId: '889900014128',
    projectId: 'nora-3e220',
    storageBucket: 'nora-3e220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_43dQpbOHSwRIYmTgF06SrivLWrbBh4c',
    appId: '1:889900014128:ios:1b715056d78e23a12cebf5',
    messagingSenderId: '889900014128',
    projectId: 'nora-3e220',
    storageBucket: 'nora-3e220.firebasestorage.app',
    iosBundleId: 'com.example.nora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_43dQpbOHSwRIYmTgF06SrivLWrbBh4c',
    appId: '1:889900014128:ios:1b715056d78e23a12cebf5',
    messagingSenderId: '889900014128',
    projectId: 'nora-3e220',
    storageBucket: 'nora-3e220.firebasestorage.app',
    iosBundleId: 'com.example.nora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVoaSbNjXGUn2q8PY1iIJNe4XfNctwTeo',
    appId: '1:889900014128:web:3767d15ff73d80c72cebf5',
    messagingSenderId: '889900014128',
    projectId: 'nora-3e220',
    authDomain: 'nora-3e220.firebaseapp.com',
    storageBucket: 'nora-3e220.firebasestorage.app',
    measurementId: 'G-8Y7ZWFSLYZ',
  );
}
